import type { Flight, Booking } from "../types";

export const mockFlights: Flight[] = [
	{
		id: "1",
		flightNumber: "UA101",
		airline: "UniAir",
		origin: "New York (JFK)",
		destination: "Los Angeles (LAX)",
		departureTime: "08:00",
		arrivalTime: "11:30",
		duration: "5h 30m",
		price: 299,
		seatsRemaining: 45,
	},
	{
		id: "2",
		flightNumber: "UA205",
		airline: "UniAir",
		origin: "New York (JFK)",
		destination: "Los Angeles (LAX)",
		departureTime: "14:00",
		arrivalTime: "17:30",
		duration: "5h 30m",
		price: 349,
		seatsRemaining: 12,
	},
	{
		id: "3",
		flightNumber: "UA309",
		airline: "UniAir",
		origin: "New York (JFK)",
		destination: "Los Angeles (LAX)",
		departureTime: "20:00",
		arrivalTime: "23:30",
		duration: "5h 30m",
		price: 259,
		seatsRemaining: 3,
	},
	{
		id: "4",
		flightNumber: "UA412",
		airline: "UniAir Express",
		origin: "New York (JFK)",
		destination: "Los Angeles (LAX)",
		departureTime: "06:00",
		arrivalTime: "09:15",
		duration: "5h 15m",
		price: 399,
		seatsRemaining: 28,
	},
	{
		id: "5",
		flightNumber: "UA515",
		airline: "UniAir",
		origin: "New York (JFK)",
		destination: "Los Angeles (LAX)",
		departureTime: "12:00",
		arrivalTime: "15:30",
		duration: "5h 30m",
		price: 319,
		seatsRemaining: 67,
	},
];

export const airports = [
	"New York (JFK)",
	"Los Angeles (LAX)",
	"Chicago (ORD)",
	"San Francisco (SFO)",
	"Miami (MIA)",
	"Seattle (SEA)",
	"Boston (BOS)",
	"Denver (DEN)",
	"Atlanta (ATL)",
	"Dallas (DFW)",
];

export const mockBookings: Booking[] = [
	{
		id: "1",
		pnr: "ABC123",
		flight: mockFlights[0],
		passengers: [
			{
				id: "1",
				fullName: "John Doe",
				dateOfBirth: "1995-05-15",
				nationality: "United States",
				passportNumber: "US123456789",
				email: "john@university.edu",
				phoneNumber: "+1 234 567 8900",
			},
		],
		totalPrice: 329,
		status: "confirmed",
		createdAt: "2024-01-15",
	},
];
